const colors = {
  light: {
    primary: '#007BFF',
    background: '#f8f9fa',
    card: '#ffffff',
    text: '#212529',
    border: '#dee2e6',
    notification: '#ff3b30',
    error: '#dc3545',
    success: '#28a745',
    buttonText: '#ffffff',
    inputBackground: '#ffffff',
    inputBorder: '#ced4da',
    inputText: '#495057',
    headerBackground: '#007BFF',
    headerText: '#ffffff',
    tabBarBackground: '#ffffff',
    tabBarActive: '#007BFF',
    tabBarInactive: '#888888',
    divider: '#dee2e6',
  },
  dark: {
    primary: '#0d6efd',
    background: '#121212',
    card: '#1e1e1e',
    text: '#f8f9fa',
    border: '#343a40',
    notification: '#ff453a',
    error: '#dc3545',
    success: '#28a745',
    buttonText: '#ffffff',
    inputBackground: '#2c2c2c',
    inputBorder: '#495057',
    inputText: '#e9ecef',
    headerBackground: '#0d6efd',
    headerText: '#ffffff',
    tabBarBackground: '#1e1e1e',
    tabBarActive: '#0d6efd',
    tabBarInactive: '#6c757d',
    divider: '#343a40',
  },
};

export default colors;